modLoader="javafml"
loaderVersion="[28,)"
displayURL="https://www.curseforge.com/minecraft/mc-mods/apple-trees-revived"
logoFile="banner.png"
[[mods]]
modId="appletreesrev"
version="1.4b"
displayName="Apple Trees Revived"
credits="To https://www.curseforge.com/minecraft/mc-mods/apple-trees Original Mod"
authors="Dav729"
description='''
A Personal Port from Original Apple Trees Mod.

A Simple Feature to get Apples in a simpler Way ;).
'''
[[dependencies.appletreesrev]] #optional
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.appletreesrev]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
